[btop]
title = "btop"
command = "kitty --title btop -e btop"
rules = "float;size 85% 85%;center"
options = "cover persist sticky shiny eager summon hide poly special" 

[nautilus]
title = "Loading…"
command = "nautilus"
rules = "float;size 70% 80%;center"

[noname]
title = "\\\""
command = "\\'"
options = "cover eager special"

[wierd]
title = " a program with ' a wierd ' name"
command = " a \"command with\" \\'a wierd\\' format"
options = "hide summon"
