execonce("hyprscratch init clean eager")
execonce("hyprscratch eager")
execonce("hyprscratch clean")
execonce("hyprscratch spotless")
execonce("hyprscratch no-auto-reload")

bind("$mainMod", "b", "exec", "hyprscratch cycle")
bind("$mainMod", "b", "exec", "hyprscratch cycle special")
bind("$mainMod", "b", "exec", "hyprscratch cycle normal")
bind("$mainMod", "b", "exec", "hyprscratch toggle name")
bind("$mainMod", "b", "exec", "hyprscratch show name")
bind("$mainMod", "b", "exec", "hyprscratch hide name")
bind("$mainMod", "b", "exec", "hyprscratch hide-all")
bind("$mainMod", "b", "exec", "hyprscratch get-config")
bind("$mainMod", "b", "exec", "hyprscratch reload")
bind("$mainMod", "b", "exec", "hyprscratch previous")
bind("$mainMod", "b", "exec", "hyprscratch kill")
bind("$mainMod", "b", "exec", "hyprscratch kill-all")

bind("$mainMod", "b", "exec", "hyprscratch btop '[size monitor_w*0.85 monitor_h*0.85] kitty --title btop -e btop' cover persist sticky shiny lazy show hide poly special tiled")
bind("$mainMod", "b", "exec", "hyprscratch 'Loading…' '[size monitor_w*0.7 monitor_h*0.8] nautilus'")
