btop {
    class = "btop"
    command = "kitty --title btop -e btop"
    rules = "size monitor_w*0.85 monitor_h*0.85"
    options = "cover persist sticky shiny lazy show hide poly special tiled"
}

group:one {
    nautilus {
        title=Loading…
        command=nautilus
        rules=size monitor_w*0.7 monitor_h*0.8
    }

    noname  {
        title = \\"
        command = \\'
        options = cover lazy special
    }
}

group:two {
    name = btop

    wierd = {
        class = " a program with ' a wierd ' name"
        command = "a \"command with\" \\'a wierd\\' format"
        options = hide show
    }
}

group:three {
    name = btop
    name = noname
}
